app:
  auth-server: localhost
  config-server: localhost

# applying graceful shutdown, a microservice stops accepting new requests
# and waits for a configurable time for active requests to complete before
# it shuts down the application.
server.shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 10s

management.health.kafka.enabled: true
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: health,info,circuitbreakerevents
# To briefly recap, a liveness probe tells Kubernetes if a Pod needs to be replaced,
# and a readiness probe tells Kubernetes if its Pod is ready to accept requests.
# To simplify this work, Spring Boot has added support to implement liveness and readiness probes.
# exposed on the URLs /actuator/health/liveness and /actuator/health/readiness
management.endpoint.health.probes.enabled: true
management.endpoint.health.group.readiness.include: readinessState

# Common configurations
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  server:
    requests:
      ignore-patterns: /actuator/**
  observations:
    redis:
      enabled: true
    mongo:
      enabled: true
    jdbc:
      enabled: true

spring:
  codec:
    log-request-details: true
  cloud:
    stream:
      kafka:
        binder:
          enableObservation: true

logging:
  level:
    root: INFO
    com.example: INFO
    org.springframework: INFO
    org.hibernate: WARN
  logstash:
    enabled: true
    destination: localhost:5044
    connection-timeout: 5000
    reconnection-delay: 1000
    queue-size: 512

springdoc.api-docs.path: /api-docs
springdoc.swagger-ui.path: /swagger-ui.html
---
spring.config.activate.on-profile: docker

app:
  auth-server: auth-server

logging:
  logstash:
    destination: logstash:5044