server.port:
  80

spring.application.name: auth-server

app:
  eureka-username: admin
  eureka-password: admin
  eureka-server: localhost

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
#    initialInstanceInfoReplicationIntervalSeconds: 5
#    registryFetchIntervalSeconds: 5
#  instance:
#    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 5
#    leaseExpirationDurationInSeconds: 5

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.example: DEBUG
    org.hibernate: ERROR

auth0:
  domain: ${AUTH_DOMAIN}
  clientId: ${AUTH_CLIENT_ID}
  clientSecret: ${AUTH_CLIENT_SECRET}
  audience: ${AUTH_AUDIENCE}
  redirectUri: ${AUTH_REDIRECT_URI}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI}
          audience: ${AUTH_AUDIENCE}
---
spring.config.activate.on-profile: docker
server.port: 80