server.port: 7001
management.endpoint.health.show-details: "ALWAYS"

app:
  eureka-username: admin
  eureka-password: admin

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productdb
      auto-index-creation: true

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.example: INFO
    org.hibernate: ERROR
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings.deleteMessageProcessor-in-0:
    destination: productTopic
    group: productsGroup
    consumer:
      maxAttempts: 3
      backOffInitialInterval: 500
      backOffMaxInterval: 1000
      backOffMultiplier: 2.0

spring.cloud.stream.kafka.bindings.deleteMessageProcessor-in-0.consumer:
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: kafka
  defaultBrokerPort: 9092

# To allow observability
spring.cloud.stream.kafka.binder.enableObservation: true

# Observability in your MongoDB
# Disable Spring Boot's autoconfigured tracing
management.metrics.mongo.command.enabled: false
# Enable it manually
management.tracing.enabled: true

spring.application.name: product

app.eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---
spring.config.activate.on-profile: docker

server.port: 8081

app.eureka-server: discovery

# discovery here is the name of the eureka's k8 service
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@discovery:8761/eureka/

spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: productdb
      auto-index-creation: true

spring.cloud.stream.kafka.binder.brokers: kafka