server:
  port: 7003
management.endpoint.health.show-details: "ALWAYS"

app:
  eureka-username: admin
  eureka-password: admin

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reviewdb?allowPublicKeyRetrieval=true&useSSL=false
    username: joice
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings.reviewMessageProcessor-in-0:
    destination: reviewTopic
    group: reviewsGroup
    consumer:
      maxAttempts: 3
      backOffInitialInterval: 500
      backOffMaxInterval: 1000
      backOffMultiplier: 2.0

spring.cloud.stream.kafka.bindings.deleteMessageProcessor-in-0.consumer:
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: kafka
  defaultBrokerPort: 9092

# To allow observability
spring.cloud.stream.kafka.binder.enableObservation: true

spring.application.name: review

app.eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

logging:
  level:
    root: ERROR
    org.springframework.web: INFO
    com.example: INFO
    org.hibernate: ERROR

---
spring.config.activate.on-profile: docker

server.port: 8082

app.eureka-server: discovery

# discovery here is the name of the eureka's k8 service
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@discovery:8761/eureka/

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.example: INFO
    org.hibernate: ERROR

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/reviewdb
    username: joice
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

spring.cloud.stream.kafka.binder.brokers: kafka