{{- define "common.secrets" -}}
  # begins a loop using the range function, iterating over each Secret defined in
  # the .Values.secrets section of the chart's values file
  {{- range $secretName, $secretMap := .Values.secrets }}
  # The range function assigns the current Secret name and its map to
  # the variables $secretName and $secretMap.
  # For each secret in .Values.secrets, it sets the Secret's metadata
  # including its name, labels, and managed-by field.
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/name: {{ $secretName }}
    # This line includes another template named "common.chart" and passes the current context to it using $.
    # The current context includes variables like .Values, .Release, and any other variables defined in the
    # Helm template.
    helm.sh/chart: {{ include "common.chart" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
type: Opaque
data:
  # loops over each key-value pair within the current Secret's map ($secretMap)
  # and encodes the values using base64 encoding (b64enc). This is common practice
  # for encoding sensitive data in Kubernetes Secrets.
  {{- range $key, $val := $secretMap }}
    {{ $key }}: {{ $val | b64enc }}
  {{- end }}
# The --- is used to separate the rendered Secret manifests from each other so that they are processed
# as separate YAML documents.
---
{{- end -}}
  {{- end -}}