fullnameOverride: zipkin

image:
  repository: registry.hub.docker.com/openzipkin
  name: zipkin
  tag: 2.24.0
  pullPolicy: IfNotPresent

env:
  STORAGE_TYPE: elasticsearch
  ES_HOSTS: http://elasticsearch:9200
  JAVA_OPTS: -Xms512m -Xmx1g

ports:
  - name: http
    containerPort: 9411
    protocol: 'TCP'

livenessProbe_enabled: true
livenessProbe:
  httpGet:
    scheme: HTTP
    path: /actuator/info
    port: 9411
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 20
  successThreshold: 1

readinessProbe_enabled: true
readinessProbe:
  httpGet:
    scheme: HTTP
    path: /actuator/health
    port: 9411
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1

resources:
  requests:
    memory: "512Mi"  # Minimum memory guaranteed
  limits:
    memory: "1Gi"    # Maximum memory allowed before OOMKill

service:
  ports:
    - port: 9411
      targetPort: 9411
      protocol: 'TCP'
      name: http

# Zipkin dependency job configuration
dependency:
  enabled: true
  schedule: "0 */1 * * *"  # Run every hour
  image:
    repository: registry.hub.docker.com/openzipkin/zipkin-dependencies
    tag: latest
    pullPolicy: IfNotPresent
  env:
    - name: STORAGE_TYPE
      value: elasticsearch
    - name: ES_HOSTS
      value: http://elasticsearch:9200
    # Reuse the same ES configuration from the main Zipkin service
    # Add any additional dependency-specific environment variables here
  resources:
    requests:
      memory: "256Mi"
    limits:
      memory: "1Gi"
  restartPolicy: OnFailure