fullnameOverride: gateway

image:
  name: gateway

ports:
  - containerPort: 8443

env:
  SPRING_PROFILES_ACTIVE: "docker"

livenessProbe_enabled: true
livenessProbe:
  httpGet:
    scheme: HTTPS
    port: 8443
readinessProbe_enabled: true
readinessProbe:
  httpGet:
    scheme: HTTPS
    port: 8443

service:
  type: NodePort
  ports:
    - port: 443 # port number on which the Service will be exposed within the Kubernetes cluster. ClusterIP port
      targetPort: 8443 # port number on the Pod to which traffic should be forwarded. Container port
      nodePort: 30443 # allows external traffic (outside the Kubernetes cluster) to access the Service directly through the node's IP address and the specified nodePort.