server.port: 7000
management.endpoint.health.show-details: "ALWAYS"

spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings:
    productDelete-out-0:
      destination: productTopic # topic/exchange name
      producer:
        required-groups: auditGroup # this property when used with Kafka, events are retained in separate topics, even after consumers have processed them.
    reviewDelete-out-0:
      destination: reviewTopic
      producer:
        required-groups: auditGroup

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring.application.name: composite

app.eureka-server: localhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.example: DEBUG
    org.hibernate: ERROR

---
spring.config.activate.on-profile: docker

server.port: 8083

spring.cloud.stream.kafka.binder.brokers: kafka

app.eureka-server: discovery

