server.port: 7000

app:
 product-service:
  host: localhost
  port: 7001
 review-service:
  host: localhost
  port: 7003

logging:
 level:
  root: ERROR
  org.springframework.web: ERROR
  com.example: DEBUG
  org.hibernate: ERROR

---
spring.config.activate.on-profile: docker

app:
 product-service:
  host: product
  port: 8081
 review-service:
  host: review
  port: 8082

logging:
 level:
  root: ERROR
  org.springframework.web: ERROR
  com.example: DEBUG
  org.hibernate: ERROR