fullnameOverride: product

image:
  name: product

env:
  SPRING_PROFILES_ACTIVE: "docker"

ports:
  - name: http
    containerPort: 8081
    protocol: TCP

livenessProbe_enabled: true
livenessProbe:
  httpGet:
    port: 8081
readinessProbe_enabled: true
readinessProbe:
  httpGet:
    port: 8081

service:
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http