server:
  port: 8761

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.example: DEBUG
    org.hibernate: ERROR

# standard configuration for a standalone Eureka server.
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  #used to minimize the startup time.
  server:
    waitTimeInMsWhenSyncEmpty: 0
    response-cache-update-interval-ms: 5000

management.endpoints.web.exposure.include: "*"