app:
  auction-service: localhost

spring:
  application.name: auction
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auctionbiddb?allowPublicKeyRetrieval=true&useSSL=false
    username: joice
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings:
    bidProcessor-in-0:
      destination: bidTopic
      group: bidGroup
      consumer:
        enableDlq: true
        maxAttempts: 3
        backOffInitialInterval: 500
        backOffMaxInterval: 3000
        backOffMultiplier: 2.0
    bidPlace-out-0:
      destination: bidTopic
      producer:
        required-groups: auditGroup

spring.cloud.stream.kafka.binder:
  brokers: localhost
  defaultBrokerPort: 9092
#spring.cloud.stream.kafka.binder:
#  brokers: kafka
#  defaultBrokerPort: 9092


springdoc.api-docs.path: /api-docs
springdoc.swagger-ui.path: /swagger-ui.html

---
spring.config.activate.on-profile: docker

server.port: 8084

app.eureka-server: auction

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/auctionbiddb
    username: joice
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

spring.cloud.stream.kafka.binder.brokers: kafka

## To be removed in deployment
management.zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability: 1.0
logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
spring.codec.log-request-details: true