server.port: 7001
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productdb

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.example: DEBUG
    org.hibernate: ERROR

spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings.deleteMessageProcessor-in-0:
    destination: productsTopic
    group: productsGroup
    consumer:
      maxAttempts: 3
      backOffInitialInterval: 500
      backOffMaxInterval: 1000
      backOffMultiplier: 2.0

spring.cloud.stream.kafka.bindings.deleteMessageProcessor-in-0.consumer:
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

---
spring.config.activate.on-profile: docker

server.port: 8081

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.example: DEBUG
    org.hibernate: ERROR

spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: productdb

spring.cloud.stream.kafka.binder.brokers: kafka