server.port: 7001
management.endpoint.health.show-details: "ALWAYS"

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productdb

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.example: DEBUG
    org.hibernate: ERROR

spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings.deleteMessageProcessor-in-0:
    destination: productTopic
    group: productsGroup
    consumer:
      maxAttempts: 3
      backOffInitialInterval: 500
      backOffMaxInterval: 1000
      backOffMultiplier: 2.0

spring.cloud.stream.kafka.bindings.deleteMessageProcessor-in-0.consumer:
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring.application.name: product

app.eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---
spring.config.activate.on-profile: docker

server.port: 8081

eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka/

spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: productdb

spring.cloud.stream.kafka.binder.brokers: kafka