server.port: 8888

spring.cloud.config.server.native.searchLocations: file:${PWD}/config-repo

management.endpoint.health.show-details: "ALWAYS"
management.endpoint.web.exposure.include: "*"

logging:
  level:
    root: info

---
spring.config.activate.on-profile: docker

spring.cloud.config.server.native.searchLocations: file:/config-repo

